---
- name: Install Centos Dependency
  hosts: localhost
  become: true
  connection: local
  tasks: 
  - name: Install the latest version of Apache
    yum:
      name: httpd
      state: latest
  - name: enable httpd
    service: name=httpd enabled=yes state=started